title: "GitHub Pages"
description: "Paper Reviews Â· Server & DevOps"
url: "https://jjiabcd.github.io"
baseurl: "/github-pages"
markdown: kramdown

exclude:
  - workspace/
  - .vscode/
  - .gitignore
  - README.md
