title: "Jin's blog"
description: "Cheminformatics & ML/DL Study Notes"
url: "https://jjiabcd.github.io"
baseurl: "/github-pages"
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

exclude:
  - workspace/
  - .vscode/
  - .gitignore
  - README.md

collections:
  tag:
    output: true
    permalink: /tag/:name/