title: "Jin's blog"
description: "Cheminformatics & ML/DL Study Notes"
url: "https://jjiabcd.github.io"
baseurl: "/github-pages"
markdown: kramdown

exclude:
  - workspace/
  - .vscode/
  - .gitignore
  - README.md
